# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-16 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
