# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_delete_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hacker',
            old_name='description',
            new_name='profile_about',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='git',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='voted_for',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='website',
        ),
        migrations.AddField(
            model_name='hacker',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hacker',
            name='profile_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
