# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180917_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='team',
        ),
    ]
