# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('git', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
